
version: "3.9"

services:

  db:
    image: postgres:14.3-alpine3.15
    ports:
      - "5432:5432"
    hostname: localhost
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
